obj-$(CONFIG_FLX_FRS) += flx_frs.o
flx_frs-objs := flx_frs_main.o flx_frs_proc.o flx_frs_mmio.o \
	flx_frs_netdev.o flx_frs_netdevif.o \
	flx_frs_ioctl.o flx_frs_hw.o flx_frs_ethtool.o \
	flx_frs_adapter.o flx_frs_sfp.o flx_frs_aux_netdev.o
obj-$(CONFIG_FLX_BUS)	+= flx_frs_indirect.o
obj-$(CONFIG_NET_SWITCHDEV)	+= flx_frs_switchdev.o

